// <auto-generated />
using System;
using HomeWeather.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HomeWeather.Data.Migrations
{
    [DbContext(typeof(HomeWeatherContext))]
    partial class HomeWeatherContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.HasSequence("snID");

            modelBuilder.HasSequence("thID");

            modelBuilder.Entity("HomeWeather.Data.Entities.Sensor", b =>
                {
                    b.Property<long>("snID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("NEXT VALUE FOR snID");

                    b.Property<DateTime?>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime?>("EditAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ROM")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("snID");

                    b.ToTable("Sensors");
                });

            modelBuilder.Entity("HomeWeather.Data.Entities.TempHistory", b =>
                {
                    b.Property<int>("thID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR thID");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<float>("Temperature")
                        .HasColumnType("real");

                    b.Property<long>("snID")
                        .HasColumnType("bigint");

                    b.HasKey("thID");

                    b.HasIndex("snID");

                    b.ToTable("TempHistory");
                });

            modelBuilder.Entity("HomeWeather.Data.Entities.TempHistory", b =>
                {
                    b.HasOne("HomeWeather.Data.Entities.Sensor", "Sensors")
                        .WithMany()
                        .HasForeignKey("snID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sensors");
                });
#pragma warning restore 612, 618
        }
    }
}
